vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        images:
            uri_prefix: /images/dessins
            upload_destination: '%kernel.project_dir%/public/images/dessins'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
